# Site settings
title: The World According to Sound | A 90 second podcast
email: ""
description: ""
baseurl: ""
url: "http://www.theworldaccordingtosound.org"
# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
gems: [jekyll-coffeescript]
